const actionTypes = {
  GET_NEWS_REQUESTED: 'GET_NEWS_REQUESTED',
  GET_NEWS_SUCCESS: 'GET_NEWS_SUCCESS',
  GET_NEWS_REJECTED: 'GET_NEWS_REJECTED',

  REGISTRATION_REQUESTED: 'REGISTRATION_REQUESTED',
  REGISTRATION_SUCCESS: 'REGISTRATION_SUCCESS',
  REGISTRATION_REJECTED: 'REGISTRATION_REJECTED',

  LOGIN_REQUESTED: 'LOGIN_REQUESTED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_REJECTED: 'LOGIN_REJECTED',

  LOGOUT_REQUESTED: 'LOGOUT_REQUESTED',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_REJECTED: 'LOGOUT_REJECTED',

  REFRESH_REQUESTED: 'REFRESH_REQUESTED',
  REFRESH_SUCCESS: 'REFRESH_SUCCESS',
  REFRESH_REJECTED: 'REFRESH_REJECTED',

  WHOAMI_REQUESTED: 'WHOAMI_REQUESTED',
  WHOAMI_SUCCESS: 'WHOAMI_SUCCESS',
  WHOAMI_REJECTED: 'WHOAMI_REJECTED',

  USER_PAGE_REQUESTED: 'USER_PAGE_REQUESTED',
  USER_PAGE_SUCCESS: 'USER_PAGE_SUCCESS',
  USER_PAGE_REJECTED: 'USER_PAGE_REJECTED',
};

export default actionTypes;
